# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bryan Lim
email: ytbryan.com
description: > # this means to ignore newlines until "baseurl:"
  I am the founder of The Amazing Digital Asia which was started in 2011. We do custom software and programming consulting. Currently I am staying in Singapore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ytbryan.com" # the base hostname & protocol for your site
twitter_username: ytbryan
github_username:  ytbryan
facebook_username:  bryanlim
stackoverflow_usersname: ytbryan
clicky:
  trackingid: 100784720

# Build settings
markdown: kramdown
paginate: 7
paginate_path: "/page/:num"
gems:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
